export type Temperament = "peaceful" | "semi-aggressive" | "aggressive";
export type SwimmingLevel = "top" | "middle" | "bottom" | "all";
export type Diet = "omnivore" | "herbivore" | "carnivore";

export interface FishProfile {
  name: string;
  scientificName: string;
  temperament: Temperament;
  minSizeCm: number;
  maxSizeCm: number;
  minPh: number;
  maxPh: number;
  minTempC: number;
  maxTempC: number;
  minTankLitres: number;
  swimmingLevel: SwimmingLevel;
  schooling: boolean;
  diet: Diet;
  speciesGroup: string;
}

export const fishDatabase = {
  angelfish: {
    name: "Angelfish",
    scientificName: "Pterophyllum scalare",
    temperament: "semi-aggressive",
    minSizeCm: 10,
    maxSizeCm: 15,
    minPh: 6,
    maxPh: 7.5,
    minTempC: 24,
    maxTempC: 30,
    minTankLitres: 150,
    swimmingLevel: "middle",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "cichlid",
  },
  betta: {
    name: "Betta (Siamese Fighting Fish)",
    scientificName: "Betta splendens",
    temperament: "aggressive",
    minSizeCm: 5,
    maxSizeCm: 7,
    minPh: 6,
    maxPh: 8,
    minTempC: 24,
    maxTempC: 30,
    minTankLitres: 20,
    swimmingLevel: "top",
    schooling: false,
    diet: "carnivore",
    speciesGroup: "betta",
  },
  bristlenose_pleco: {
    name: "Bristlenose Pleco",
    scientificName: "Ancistrus cirrhosus",
    temperament: "peaceful",
    minSizeCm: 10,
    maxSizeCm: 15,
    minPh: 5.8,
    maxPh: 7.8,
    minTempC: 23,
    maxTempC: 27,
    minTankLitres: 100,
    swimmingLevel: "bottom",
    schooling: false,
    diet: "herbivore",
    speciesGroup: "pleco",
  },
  cardinal_tetra: {
    name: "Cardinal Tetra",
    scientificName: "Paracheirodon axelrodi",
    temperament: "peaceful",
    minSizeCm: 3,
    maxSizeCm: 5,
    minPh: 4.5,
    maxPh: 7,
    minTempC: 23,
    maxTempC: 29,
    minTankLitres: 40,
    swimmingLevel: "middle",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "tetra",
  },
  cherry_barb: {
    name: "Cherry Barb",
    scientificName: "Puntius titteya",
    temperament: "peaceful",
    minSizeCm: 3,
    maxSizeCm: 5,
    minPh: 6,
    maxPh: 8,
    minTempC: 23,
    maxTempC: 27,
    minTankLitres: 50,
    swimmingLevel: "middle",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "barb",
  },
  corydoras: {
    name: "Corydoras Catfish",
    scientificName: "Corydoras paleatus",
    temperament: "peaceful",
    minSizeCm: 5,
    maxSizeCm: 7,
    minPh: 6,
    maxPh: 8,
    minTempC: 22,
    maxTempC: 26,
    minTankLitres: 40,
    swimmingLevel: "bottom",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "catfish",
  },
  discus: {
    name: "Discus",
    scientificName: "Symphysodon spp.",
    temperament: "peaceful",
    minSizeCm: 12,
    maxSizeCm: 20,
    minPh: 5,
    maxPh: 7,
    minTempC: 26,
    maxTempC: 31,
    minTankLitres: 200,
    swimmingLevel: "middle",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "cichlid",
  },
  dwarf_gourami: {
    name: "Dwarf Gourami",
    scientificName: "Trichogaster lalius",
    temperament: "peaceful",
    minSizeCm: 5,
    maxSizeCm: 9,
    minPh: 6,
    maxPh: 7.5,
    minTempC: 22,
    maxTempC: 28,
    minTankLitres: 40,
    swimmingLevel: "top",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "gourami",
  },
  endler_guppy: {
    name: "Endler's Livebearer",
    scientificName: "Poecilia wingei",
    temperament: "peaceful",
    minSizeCm: 2.5,
    maxSizeCm: 4.5,
    minPh: 6.5,
    maxPh: 8.5,
    minTempC: 24,
    maxTempC: 30,
    minTankLitres: 30,
    swimmingLevel: "top",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "livebearer",
  },
  german_blue_ram: {
    name: "German Blue Ram",
    scientificName: "Mikrogeophagus ramirezi",
    temperament: "peaceful",
    minSizeCm: 5,
    maxSizeCm: 7,
    minPh: 5,
    maxPh: 7,
    minTempC: 25,
    maxTempC: 30,
    minTankLitres: 75,
    swimmingLevel: "bottom",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "cichlid",
  },
  guppy: {
    name: "Guppy",
    scientificName: "Poecilia reticulata",
    temperament: "peaceful",
    minSizeCm: 3,
    maxSizeCm: 6,
    minPh: 6.8,
    maxPh: 7.8,
    minTempC: 22,
    maxTempC: 28,
    minTankLitres: 40,
    swimmingLevel: "top",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "livebearer",
  },
  harlequin_rasbora: {
    name: "Harlequin Rasbora",
    scientificName: "Trigonostigma heteromorpha",
    temperament: "peaceful",
    minSizeCm: 3,
    maxSizeCm: 5,
    minPh: 5,
    maxPh: 7.5,
    minTempC: 22,
    maxTempC: 28,
    minTankLitres: 40,
    swimmingLevel: "middle",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "rasbora",
  },
  honey_gourami: {
    name: "Honey Gourami",
    scientificName: "Trichogaster chuna",
    temperament: "peaceful",
    minSizeCm: 4,
    maxSizeCm: 5,
    minPh: 6,
    maxPh: 7.5,
    minTempC: 22,
    maxTempC: 28,
    minTankLitres: 40,
    swimmingLevel: "top",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "gourami",
  },
  kuhli_loach: {
    name: "Kuhli Loach",
    scientificName: "Pangio kuhlii",
    temperament: "peaceful",
    minSizeCm: 7,
    maxSizeCm: 10,
    minPh: 5.5,
    maxPh: 7,
    minTempC: 24,
    maxTempC: 30,
    minTankLitres: 60,
    swimmingLevel: "bottom",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "loach",
  },
  molly: {
    name: "Molly",
    scientificName: "Poecilia sphenops",
    temperament: "peaceful",
    minSizeCm: 6,
    maxSizeCm: 10,
    minPh: 7,
    maxPh: 8.5,
    minTempC: 22,
    maxTempC: 28,
    minTankLitres: 75,
    swimmingLevel: "middle",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "livebearer",
  },
  neon_tetra: {
    name: "Neon Tetra",
    scientificName: "Paracheirodon innesi",
    temperament: "peaceful",
    minSizeCm: 2.5,
    maxSizeCm: 3.5,
    minPh: 5,
    maxPh: 7.5,
    minTempC: 20,
    maxTempC: 28,
    minTankLitres: 40,
    swimmingLevel: "middle",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "tetra",
  },
  oscar: {
    name: "Oscar",
    scientificName: "Astronotus ocellatus",
    temperament: "aggressive",
    minSizeCm: 25,
    maxSizeCm: 35,
    minPh: 6,
    maxPh: 8,
    minTempC: 23,
    maxTempC: 28,
    minTankLitres: 280,
    swimmingLevel: "middle",
    schooling: false,
    diet: "carnivore",
    speciesGroup: "cichlid",
  },
  otocinclus: {
    name: "Otocinclus",
    scientificName: "Otocinclus vittatus",
    temperament: "peaceful",
    minSizeCm: 3,
    maxSizeCm: 5,
    minPh: 6,
    maxPh: 7.5,
    minTempC: 22,
    maxTempC: 28,
    minTankLitres: 40,
    swimmingLevel: "bottom",
    schooling: true,
    diet: "herbivore",
    speciesGroup: "catfish",
  },
  pearl_gourami: {
    name: "Pearl Gourami",
    scientificName: "Trichopodus leerii",
    temperament: "peaceful",
    minSizeCm: 10,
    maxSizeCm: 12,
    minPh: 5.5,
    maxPh: 7.5,
    minTempC: 24,
    maxTempC: 28,
    minTankLitres: 100,
    swimmingLevel: "top",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "gourami",
  },
  platy: {
    name: "Platy",
    scientificName: "Xiphophorus maculatus",
    temperament: "peaceful",
    minSizeCm: 4,
    maxSizeCm: 7,
    minPh: 7,
    maxPh: 8.2,
    minTempC: 20,
    maxTempC: 28,
    minTankLitres: 40,
    swimmingLevel: "middle",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "livebearer",
  },
  rummy_nose_tetra: {
    name: "Rummy Nose Tetra",
    scientificName: "Hemigrammus rhodostomus",
    temperament: "peaceful",
    minSizeCm: 4,
    maxSizeCm: 5,
    minPh: 5.5,
    maxPh: 7,
    minTempC: 24,
    maxTempC: 28,
    minTankLitres: 60,
    swimmingLevel: "middle",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "tetra",
  },
  siamese_algae_eater: {
    name: "Siamese Algae Eater",
    scientificName: "Crossocheilus oblongus",
    temperament: "peaceful",
    minSizeCm: 10,
    maxSizeCm: 16,
    minPh: 6,
    maxPh: 8,
    minTempC: 24,
    maxTempC: 26,
    minTankLitres: 100,
    swimmingLevel: "bottom",
    schooling: false,
    diet: "herbivore",
    speciesGroup: "algae_eater",
  },
  swordtail: {
    name: "Swordtail",
    scientificName: "Xiphophorus hellerii",
    temperament: "peaceful",
    minSizeCm: 8,
    maxSizeCm: 14,
    minPh: 7,
    maxPh: 8.4,
    minTempC: 22,
    maxTempC: 28,
    minTankLitres: 75,
    swimmingLevel: "middle",
    schooling: false,
    diet: "omnivore",
    speciesGroup: "livebearer",
  },
  tiger_barb: {
    name: "Tiger Barb",
    scientificName: "Puntigrus tetrazona",
    temperament: "semi-aggressive",
    minSizeCm: 5,
    maxSizeCm: 7,
    minPh: 6,
    maxPh: 8,
    minTempC: 20,
    maxTempC: 26,
    minTankLitres: 75,
    swimmingLevel: "middle",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "barb",
  },
  white_cloud_minnow: {
    name: "White Cloud Mountain Minnow",
    scientificName: "Tanichthys albonubes",
    temperament: "peaceful",
    minSizeCm: 3,
    maxSizeCm: 4,
    minPh: 6,
    maxPh: 8,
    minTempC: 15,
    maxTempC: 22,
    minTankLitres: 40,
    swimmingLevel: "top",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "minnow",
  },
  zebra_danio: {
    name: "Zebra Danio",
    scientificName: "Danio rerio",
    temperament: "peaceful",
    minSizeCm: 4,
    maxSizeCm: 6,
    minPh: 6,
    maxPh: 8,
    minTempC: 18,
    maxTempC: 26,
    minTankLitres: 40,
    swimmingLevel: "top",
    schooling: true,
    diet: "omnivore",
    speciesGroup: "danio",
  },
} as const satisfies Record<string, FishProfile>;

export type FishId = keyof typeof fishDatabase;

export interface FishOption extends FishProfile {
  fishId: FishId;
}

export const fishOptions: FishOption[] = Object.entries(fishDatabase)
  .map(([fishId, fish]) => ({
    fishId: fishId as FishId,
    ...fish,
  }))
  .sort((left, right) => left.name.localeCompare(right.name));
