/**
 * Fish Knowledge Base – 50 common freshwater species
 * Design: "Field Guide" editorial style
 * Each entry encodes biological and behavioural attributes for compatibility inference.
 */

export interface FishSpecies {
  id: string;
  commonName: string;
  scientificName: string;
  sizeMin: number; // cm
  sizeMax: number; // cm
  phMin: number;
  phMax: number;
  tempMin: number; // °C
  tempMax: number; // °C
  minTankSize: number; // litres
  temperament: "peaceful" | "semi-aggressive" | "aggressive";
  swimLevel: "top" | "middle" | "bottom" | "all";
  schooling: boolean;
  minSchoolSize: number;
  diet: string;
  category: string;
  description: string;
}

export const FISH_DATABASE: FishSpecies[] = [
  // ── TETRAS (7) ──────────────────────────────────────────
  {
    id: "neon_tetra",
    commonName: "Neon Tetra",
    scientificName: "Paracheirodon innesi",
    sizeMin: 2.5, sizeMax: 3.5,
    phMin: 5.0, phMax: 7.5,
    tempMin: 20, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Tetra",
    description: "A small, brilliantly coloured schooling fish prized for its iridescent blue and red stripe. Thrives in groups of six or more."
  },
  {
    id: "cardinal_tetra",
    commonName: "Cardinal Tetra",
    scientificName: "Paracheirodon axelrodi",
    sizeMin: 3.0, sizeMax: 5.0,
    phMin: 4.5, phMax: 7.0,
    tempMin: 23, tempMax: 29,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Tetra",
    description: "Similar to the Neon Tetra but with a fuller red stripe extending the length of the body. Prefers soft, acidic water."
  },
  {
    id: "rummy_nose_tetra",
    commonName: "Rummy Nose Tetra",
    scientificName: "Hemigrammus rhodostomus",
    sizeMin: 4.0, sizeMax: 5.0,
    phMin: 5.5, phMax: 7.0,
    tempMin: 24, tempMax: 28,
    minTankSize: 60,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Tetra",
    description: "Named for its vivid red nose, this tight-schooling tetra is a favourite for planted tanks. Sensitive to water quality changes."
  },
  {
    id: "ember_tetra",
    commonName: "Ember Tetra",
    scientificName: "Hyphessobrycon amandae",
    sizeMin: 1.5, sizeMax: 2.0,
    phMin: 5.5, phMax: 7.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 30,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Tetra",
    description: "A tiny, fiery-orange tetra perfect for nano tanks. Peaceful and undemanding, it glows beautifully under planted-tank lighting."
  },
  {
    id: "black_skirt_tetra",
    commonName: "Black Skirt Tetra",
    scientificName: "Gymnocorymbus ternetzi",
    sizeMin: 5.0, sizeMax: 7.5,
    phMin: 6.0, phMax: 8.0,
    tempMin: 20, tempMax: 26,
    minTankSize: 60,
    temperament: "semi-aggressive",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Tetra",
    description: "A hardy tetra with flowing black fins. Can be a fin-nipper when kept in small groups — keep in schools of 6+ to reduce aggression."
  },
  {
    id: "congo_tetra",
    commonName: "Congo Tetra",
    scientificName: "Phenacogrammus interruptus",
    sizeMin: 6.0, sizeMax: 8.5,
    phMin: 6.0, phMax: 7.5,
    tempMin: 23, tempMax: 28,
    minTankSize: 100,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Tetra",
    description: "A large, iridescent tetra from the Congo River basin. Males display stunning rainbow sheens and flowing fin extensions."
  },
  {
    id: "serpae_tetra",
    commonName: "Serpae Tetra",
    scientificName: "Hyphessobrycon eques",
    sizeMin: 3.0, sizeMax: 5.0,
    phMin: 5.0, phMax: 7.8,
    tempMin: 22, tempMax: 28,
    minTankSize: 60,
    temperament: "semi-aggressive",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Tetra",
    description: "A deep-red tetra with a distinctive black shoulder spot. Known for fin-nipping behaviour, especially towards slow-moving tankmates."
  },

  // ── BETTA (1) ───────────────────────────────────────────
  {
    id: "betta",
    commonName: "Betta (Siamese Fighting Fish)",
    scientificName: "Betta splendens",
    sizeMin: 5.0, sizeMax: 7.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 24, tempMax: 30,
    minTankSize: 20,
    temperament: "aggressive",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Carnivore",
    category: "Labyrinth",
    description: "A stunningly beautiful labyrinth fish known for its flowing fins. Males are highly territorial towards other males and similar-looking species."
  },

  // ── LIVEBEARERS (5) ─────────────────────────────────────
  {
    id: "guppy",
    commonName: "Guppy",
    scientificName: "Poecilia reticulata",
    sizeMin: 3.0, sizeMax: 6.0,
    phMin: 6.8, phMax: 7.8,
    tempMin: 22, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Livebearer",
    description: "A colourful, hardy livebearer popular with beginners. Males display vibrant tail patterns. Breeds readily in community tanks."
  },
  {
    id: "endler_guppy",
    commonName: "Endler's Livebearer",
    scientificName: "Poecilia wingei",
    sizeMin: 2.5, sizeMax: 4.5,
    phMin: 6.5, phMax: 8.5,
    tempMin: 24, tempMax: 30,
    minTankSize: 30,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Livebearer",
    description: "A smaller, more colourful cousin of the common guppy. Males display vivid neon patterns. Hardy and prolific breeders."
  },
  {
    id: "platy",
    commonName: "Platy",
    scientificName: "Xiphophorus maculatus",
    sizeMin: 4.0, sizeMax: 7.0,
    phMin: 7.0, phMax: 8.2,
    tempMin: 20, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Livebearer",
    description: "A cheerful, easy-going livebearer available in many colour varieties. Excellent community fish that prefers slightly alkaline water."
  },
  {
    id: "molly",
    commonName: "Molly",
    scientificName: "Poecilia sphenops",
    sizeMin: 6.0, sizeMax: 10.0,
    phMin: 7.0, phMax: 8.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 75,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Livebearer",
    description: "A versatile livebearer that adapts to a range of conditions. Prefers hard, alkaline water and benefits from some vegetable matter in its diet."
  },
  {
    id: "swordtail",
    commonName: "Swordtail",
    scientificName: "Xiphophorus hellerii",
    sizeMin: 8.0, sizeMax: 14.0,
    phMin: 7.0, phMax: 8.4,
    tempMin: 22, tempMax: 28,
    minTankSize: 75,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Livebearer",
    description: "Named for the elongated lower tail fin of males. Active swimmers that appreciate a well-planted tank with open swimming space."
  },

  // ── CATFISH & PLECOS (6) ────────────────────────────────
  {
    id: "corydoras",
    commonName: "Corydoras Catfish",
    scientificName: "Corydoras paleatus",
    sizeMin: 5.0, sizeMax: 7.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 22, tempMax: 26,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Catfish",
    description: "A charming, armoured bottom-dweller that constantly forages for food. Social fish that should be kept in groups of six or more."
  },
  {
    id: "pygmy_corydoras",
    commonName: "Pygmy Corydoras",
    scientificName: "Corydoras pygmaeus",
    sizeMin: 2.0, sizeMax: 3.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 22, tempMax: 26,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: true, minSchoolSize: 8,
    diet: "Omnivore",
    category: "Catfish",
    description: "One of the smallest corydoras species. Unlike other cories, it often hovers in midwater. Best kept in groups of 8+ in a nano or planted tank."
  },
  {
    id: "glass_catfish",
    commonName: "Glass Catfish",
    scientificName: "Kryptopterus vitreolus",
    sizeMin: 8.0, sizeMax: 15.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 80,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Carnivore",
    category: "Catfish",
    description: "A completely transparent fish — you can see its skeleton and organs. Shy and peaceful, it hovers in midwater in tight groups."
  },
  {
    id: "otocinclus",
    commonName: "Otocinclus",
    scientificName: "Otocinclus vittatus",
    sizeMin: 3.0, sizeMax: 5.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: true, minSchoolSize: 6,
    diet: "Herbivore",
    category: "Catfish",
    description: "A tiny, peaceful algae eater that works tirelessly on biofilm and soft algae. Best kept in groups in a mature, planted tank."
  },
  {
    id: "bristlenose_pleco",
    commonName: "Bristlenose Pleco",
    scientificName: "Ancistrus cirrhosus",
    sizeMin: 10.0, sizeMax: 15.0,
    phMin: 5.8, phMax: 7.8,
    tempMin: 23, tempMax: 27,
    minTankSize: 100,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Herbivore",
    category: "Catfish",
    description: "An excellent algae eater distinguished by the bristle-like tentacles on its snout. Nocturnal and peaceful, ideal for community tanks."
  },
  {
    id: "common_pleco",
    commonName: "Common Pleco",
    scientificName: "Hypostomus plecostomus",
    sizeMin: 30.0, sizeMax: 60.0,
    phMin: 6.5, phMax: 8.0,
    tempMin: 22, tempMax: 28,
    minTankSize: 280,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Herbivore",
    category: "Catfish",
    description: "Grows very large and requires a massive tank. Often sold as a small juvenile but can reach 60 cm. A powerful algae grazer."
  },

  // ── CICHLIDS (7) ────────────────────────────────────────
  {
    id: "angelfish",
    commonName: "Angelfish",
    scientificName: "Pterophyllum scalare",
    sizeMin: 10.0, sizeMax: 15.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 24, tempMax: 30,
    minTankSize: 150,
    temperament: "semi-aggressive",
    swimLevel: "middle",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Cichlid",
    description: "A majestic, laterally compressed cichlid with long, trailing fins. Can become territorial when breeding and may eat very small fish."
  },
  {
    id: "german_blue_ram",
    commonName: "German Blue Ram",
    scientificName: "Mikrogeophagus ramirezi",
    sizeMin: 5.0, sizeMax: 7.0,
    phMin: 5.0, phMax: 7.0,
    tempMin: 25, tempMax: 30,
    minTankSize: 75,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Cichlid",
    description: "A small, colourful dwarf cichlid with electric blue highlights. Peaceful but can be territorial around its chosen cave or spawning site."
  },
  {
    id: "oscar",
    commonName: "Oscar",
    scientificName: "Astronotus ocellatus",
    sizeMin: 25.0, sizeMax: 35.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 23, tempMax: 28,
    minTankSize: 280,
    temperament: "aggressive",
    swimLevel: "middle",
    schooling: false, minSchoolSize: 1,
    diet: "Carnivore",
    category: "Cichlid",
    description: "A large, intelligent cichlid with a strong personality. Will eat any fish small enough to fit in its mouth. Requires a very large tank."
  },
  {
    id: "discus",
    commonName: "Discus",
    scientificName: "Symphysodon spp.",
    sizeMin: 12.0, sizeMax: 20.0,
    phMin: 5.0, phMax: 7.0,
    tempMin: 26, tempMax: 31,
    minTankSize: 200,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 5,
    diet: "Omnivore",
    category: "Cichlid",
    description: "The 'king of the aquarium,' known for its disc-shaped body and vibrant patterns. Requires pristine water conditions and warm temperatures."
  },
  {
    id: "electric_blue_acara",
    commonName: "Electric Blue Acara",
    scientificName: "Andinoacara pulcher",
    sizeMin: 12.0, sizeMax: 17.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 120,
    temperament: "semi-aggressive",
    swimLevel: "middle",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Cichlid",
    description: "A stunning metallic-blue cichlid that is surprisingly peaceful for its size. Can be kept with robust community fish in a spacious tank."
  },
  {
    id: "convict_cichlid",
    commonName: "Convict Cichlid",
    scientificName: "Amatitlania nigrofasciata",
    sizeMin: 10.0, sizeMax: 15.0,
    phMin: 6.5, phMax: 8.0,
    tempMin: 22, tempMax: 28,
    minTankSize: 120,
    temperament: "aggressive",
    swimLevel: "middle",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Cichlid",
    description: "A hardy, black-and-white striped cichlid. Extremely aggressive when breeding and will defend territory against much larger fish."
  },
  {
    id: "kribensis",
    commonName: "Kribensis",
    scientificName: "Pelvicachromis pulcher",
    sizeMin: 7.0, sizeMax: 10.0,
    phMin: 5.0, phMax: 8.0,
    tempMin: 24, tempMax: 28,
    minTankSize: 75,
    temperament: "semi-aggressive",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Cichlid",
    description: "A colourful West African dwarf cichlid. Generally peaceful but becomes territorial when breeding. Females display a vibrant purple belly."
  },
  {
    id: "apistogramma",
    commonName: "Apistogramma Cacatuoides",
    scientificName: "Apistogramma cacatuoides",
    sizeMin: 5.0, sizeMax: 8.0,
    phMin: 5.0, phMax: 7.0,
    tempMin: 24, tempMax: 28,
    minTankSize: 60,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Cichlid",
    description: "A striking dwarf cichlid with elaborate dorsal fin extensions. Males are colourful and display to females. Prefers soft, acidic water."
  },

  // ── GOURAMIS (5) ────────────────────────────────────────
  {
    id: "dwarf_gourami",
    commonName: "Dwarf Gourami",
    scientificName: "Trichogaster lalius",
    sizeMin: 5.0, sizeMax: 9.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Labyrinth",
    description: "A gentle labyrinth fish with vivid orange and blue stripes. Prefers calm, well-planted tanks. Can be territorial towards other labyrinth fish."
  },
  {
    id: "pearl_gourami",
    commonName: "Pearl Gourami",
    scientificName: "Trichopodus leerii",
    sizeMin: 10.0, sizeMax: 12.0,
    phMin: 5.5, phMax: 7.5,
    tempMin: 24, tempMax: 28,
    minTankSize: 100,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Labyrinth",
    description: "One of the most attractive gouramis, covered in pearl-like spots. Peaceful and elegant, but may clash with other labyrinth fish."
  },
  {
    id: "honey_gourami",
    commonName: "Honey Gourami",
    scientificName: "Trichogaster chuna",
    sizeMin: 4.0, sizeMax: 5.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Labyrinth",
    description: "A shy, golden-yellow gourami and one of the most peaceful labyrinth fish. Ideal for calm community tanks with gentle tankmates."
  },
  {
    id: "three_spot_gourami",
    commonName: "Three Spot Gourami",
    scientificName: "Trichopodus trichopterus",
    sizeMin: 10.0, sizeMax: 15.0,
    phMin: 6.0, phMax: 8.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 100,
    temperament: "semi-aggressive",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Labyrinth",
    description: "A larger gourami that can become territorial, especially males. Available in blue, gold, and opaline colour varieties."
  },
  {
    id: "sparkling_gourami",
    commonName: "Sparkling Gourami",
    scientificName: "Trichopsis pumila",
    sizeMin: 2.5, sizeMax: 4.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 24, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: false, minSchoolSize: 1,
    diet: "Omnivore",
    category: "Labyrinth",
    description: "A tiny gourami that produces audible croaking sounds. Iridescent scales sparkle under light. Perfect for nano and planted tanks."
  },

  // ── BARBS (5) ───────────────────────────────────────────
  {
    id: "cherry_barb",
    commonName: "Cherry Barb",
    scientificName: "Puntius titteya",
    sizeMin: 3.0, sizeMax: 5.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 23, tempMax: 27,
    minTankSize: 50,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Barb",
    description: "A gentle, ruby-red barb that is an excellent community fish. Males develop a deep cherry colour during breeding. Not a fin-nipper."
  },
  {
    id: "tiger_barb",
    commonName: "Tiger Barb",
    scientificName: "Puntigrus tetrazona",
    sizeMin: 5.0, sizeMax: 7.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 20, tempMax: 26,
    minTankSize: 75,
    temperament: "semi-aggressive",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Barb",
    description: "An active, boldly striped schooling fish. Notorious fin-nipper, especially towards slow-moving, long-finned species. Best kept in large groups."
  },
  {
    id: "rosy_barb",
    commonName: "Rosy Barb",
    scientificName: "Pethia conchonius",
    sizeMin: 8.0, sizeMax: 14.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 18, tempMax: 25,
    minTankSize: 75,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Barb",
    description: "A large, rosy-pink barb that tolerates cooler temperatures. Active and hardy, making it suitable for unheated tanks in warm climates."
  },
  {
    id: "denison_barb",
    commonName: "Denison Barb",
    scientificName: "Sahyadria denisonii",
    sizeMin: 9.0, sizeMax: 15.0,
    phMin: 6.5, phMax: 7.8,
    tempMin: 15, tempMax: 25,
    minTankSize: 200,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Barb",
    description: "A striking torpedo-shaped barb with a bold red and black lateral stripe. Fast swimmer that needs a long tank with strong current."
  },
  {
    id: "gold_barb",
    commonName: "Gold Barb",
    scientificName: "Barbodes semifasciolatus",
    sizeMin: 5.0, sizeMax: 7.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 18, tempMax: 25,
    minTankSize: 75,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Barb",
    description: "A peaceful, golden-yellow barb that does well in cooler community tanks. Hardy and easy to care for, suitable for beginners."
  },

  // ── DANIOS & RASBORAS (3) ──────────────────────────────
  {
    id: "zebra_danio",
    commonName: "Zebra Danio",
    scientificName: "Danio rerio",
    sizeMin: 4.0, sizeMax: 6.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 18, tempMax: 26,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Danio",
    description: "An energetic, striped fish that darts around the upper water column. Extremely hardy and tolerant of cooler temperatures."
  },
  {
    id: "celestial_pearl_danio",
    commonName: "Celestial Pearl Danio",
    scientificName: "Danio margaritatus",
    sizeMin: 2.0, sizeMax: 3.0,
    phMin: 6.5, phMax: 7.5,
    tempMin: 20, tempMax: 26,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Danio",
    description: "A stunning micro fish covered in pearl-like white spots on a dark blue body. Males display vibrant orange fins. Ideal for planted nano tanks."
  },
  {
    id: "harlequin_rasbora",
    commonName: "Harlequin Rasbora",
    scientificName: "Trigonostigma heteromorpha",
    sizeMin: 3.0, sizeMax: 5.0,
    phMin: 5.0, phMax: 7.5,
    tempMin: 22, tempMax: 28,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Rasbora",
    description: "A graceful schooling fish with a distinctive black triangular patch. Hardy and peaceful, making it ideal for planted community tanks."
  },

  // ── LOACHES (4) ─────────────────────────────────────────
  {
    id: "kuhli_loach",
    commonName: "Kuhli Loach",
    scientificName: "Pangio kuhlii",
    sizeMin: 7.0, sizeMax: 10.0,
    phMin: 5.5, phMax: 7.0,
    tempMin: 24, tempMax: 30,
    minTankSize: 60,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Loach",
    description: "A slender, eel-like loach that hides during the day and forages at night. Peaceful and social, best kept in groups with plenty of hiding spots."
  },
  {
    id: "clown_loach",
    commonName: "Clown Loach",
    scientificName: "Chromobotia macracanthus",
    sizeMin: 15.0, sizeMax: 30.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 25, tempMax: 30,
    minTankSize: 280,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: true, minSchoolSize: 5,
    diet: "Omnivore",
    category: "Loach",
    description: "A large, colourful loach with bold orange and black bands. Social and playful but grows very large, requiring a spacious tank."
  },
  {
    id: "yoyo_loach",
    commonName: "Yoyo Loach",
    scientificName: "Botia almorhae",
    sizeMin: 10.0, sizeMax: 16.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 24, tempMax: 28,
    minTankSize: 100,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: true, minSchoolSize: 5,
    diet: "Omnivore",
    category: "Loach",
    description: "Named for the Y-O-Y-O pattern on its body. An active bottom-dweller and excellent snail controller. Social and best kept in groups."
  },
  {
    id: "dwarf_chain_loach",
    commonName: "Dwarf Chain Loach",
    scientificName: "Ambastaia sidthimunki",
    sizeMin: 4.0, sizeMax: 6.0,
    phMin: 6.0, phMax: 7.5,
    tempMin: 24, tempMax: 28,
    minTankSize: 60,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Loach",
    description: "A tiny, chain-patterned loach that is more active and visible than most loach species. Excellent for planted community tanks."
  },

  // ── RAINBOWFISH (2) ────────────────────────────────────
  {
    id: "boesemani_rainbowfish",
    commonName: "Boesemani Rainbowfish",
    scientificName: "Melanotaenia boesemani",
    sizeMin: 8.0, sizeMax: 12.0,
    phMin: 6.5, phMax: 8.0,
    tempMin: 24, tempMax: 28,
    minTankSize: 120,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Rainbowfish",
    description: "A spectacular rainbowfish with a blue front half and orange-yellow rear half. Active schooler that displays best colours in groups."
  },
  {
    id: "celebes_rainbowfish",
    commonName: "Celebes Rainbowfish",
    scientificName: "Marosatherina ladigesi",
    sizeMin: 5.0, sizeMax: 8.0,
    phMin: 7.0, phMax: 8.0,
    tempMin: 24, tempMax: 28,
    minTankSize: 60,
    temperament: "peaceful",
    swimLevel: "middle",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Rainbowfish",
    description: "A delicate, translucent rainbowfish with elongated fin filaments. Prefers slightly alkaline water and gentle current."
  },

  // ── ALGAE EATERS & MINNOWS (2) ─────────────────────────
  {
    id: "siamese_algae_eater",
    commonName: "Siamese Algae Eater",
    scientificName: "Crossocheilus oblongus",
    sizeMin: 10.0, sizeMax: 16.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 24, tempMax: 26,
    minTankSize: 100,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Herbivore",
    category: "Cyprinid",
    description: "One of the few fish that eats black beard algae. Active and generally peaceful, though it may become slightly territorial with age."
  },
  {
    id: "white_cloud_minnow",
    commonName: "White Cloud Mountain Minnow",
    scientificName: "Tanichthys albonubes",
    sizeMin: 3.0, sizeMax: 4.0,
    phMin: 6.0, phMax: 8.0,
    tempMin: 15, tempMax: 22,
    minTankSize: 40,
    temperament: "peaceful",
    swimLevel: "top",
    schooling: true, minSchoolSize: 6,
    diet: "Omnivore",
    category: "Coldwater",
    description: "A hardy coldwater schooling fish with a subtle iridescent stripe. Thrives in unheated tanks and should not be kept with tropical species."
  },

  // ── INVERTEBRATES (2) ──────────────────────────────────
  {
    id: "amano_shrimp",
    commonName: "Amano Shrimp",
    scientificName: "Caridina multidentata",
    sizeMin: 3.0, sizeMax: 5.0,
    phMin: 6.0, phMax: 7.6,
    tempMin: 16, tempMax: 27,
    minTankSize: 20,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Herbivore",
    category: "Invertebrate",
    description: "The best algae-eating shrimp in the hobby. Transparent with dotted lines along its body. Peaceful but may be eaten by larger fish."
  },
  {
    id: "cherry_shrimp",
    commonName: "Cherry Shrimp",
    scientificName: "Neocaridina davidi",
    sizeMin: 2.0, sizeMax: 3.5,
    phMin: 6.5, phMax: 8.0,
    tempMin: 18, tempMax: 28,
    minTankSize: 20,
    temperament: "peaceful",
    swimLevel: "bottom",
    schooling: false, minSchoolSize: 1,
    diet: "Herbivore",
    category: "Invertebrate",
    description: "A bright red ornamental shrimp that breeds readily in freshwater. Excellent algae cleaner but vulnerable to predation by most fish."
  },
];

export function getFishById(id: string): FishSpecies | undefined {
  return FISH_DATABASE.find(f => f.id === id);
}

export function getCategories(): string[] {
  return Array.from(new Set(FISH_DATABASE.map(f => f.category))).sort();
}
